version: '3.8'

services:
  backend:
    build: ./backend
    expose:
      - "8000"  # Доступен только внутри сети
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    depends_on:
      - db
    deploy:
      replicas: 3  # Количество реплик для бэкенда
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - my_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"  # Внешний порт
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html  # Каталог статики фронтенда
    depends_on:
      - backend
      - frontend
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge